Fix deprecated null parameter passing to htmlspecialchars
PHP 8.1 deprecated the null parameter

Fixes:

ErrorException: htmlspecialchars(): Passing null to parameter #1 ($string) of type string is deprecated in /var/www/server/index.php:164